import {render,screen,within,fireEvent,cleanup} from "@testing-library/react";
import {beforeEach,afterEach,it,expect} from "vitest";
import {CampaignPanel,CampaignHeader,CampaignOverlays,CampaignControls} from "./CampaignUI";
import {beginSession,emptyMeasurement} from "@/game/telemetry";
import {useGame} from "@/game/store";
import {saveGame,DEFAULT_META,saveMeta,loadGame} from "@/game/persist";
import {act,tick,completedReliability,combinedCompany,finishRound,finishedCompany} from "@/sim/__tests__/combinedFixture";
import type {GameState} from "@/sim";
beforeEach(()=>{localStorage.clear();useGame.setState(useGame.getInitialState(),true);});afterEach(cleanup);
function show(s:GameState){useGame.setState({game:s,ready:true,started:true,hasRun:true,onboarding:false,measurement:beginSession(emptyMeasurement(),s,"ui-test","2026-10-11T00:00:00Z")});return render(<><CampaignHeader/><CampaignPanel/><CampaignControls/><CampaignOverlays/></>);}
it("shows completed Reliability and available combined continuation without a new tree or reward",()=>{show(completedReliability());const nav=screen.getByRole("navigation",{name:"Campaign progression"});expect(nav.textContent).toContain("Stay OnlineReliability Completed");expect(nav.textContent).toContain("Grow the CompanyCombined campaign Available next");const before=useGame.getState().game.campaign!;fireEvent.click(screen.getByRole("button",{name:"Continue to Grow the Company"}));expect(useGame.getState().game.campaign!.runId).toBe(before.runId);expect(useGame.getState().game.campaign!.cashCents).toBe(before.cashCents);expect(nav.querySelector('[aria-current="step"]')!.textContent).toContain("Grow the Company");});
it("requires explicit scheduling and explains promotion cost and temporary demand",()=>{show(tick(combinedCompany(),5));expect(screen.getByRole("button",{name:"Start next growth wave"})).toBeTruthy();expect(screen.getByRole("region",{name:"Grow the Company"}).textContent).toContain("Maximum additional gross revenue is $960");fireEvent.click(screen.getByRole("button",{name:"Start next growth wave"}));expect(useGame.getState().game.campaign!.combinedStage!.currentRound!.startedStep).toBeNull();expect(screen.getByRole("button",{name:/Run promotion/}).hasAttribute("disabled")).toBe(true);});
it("dismissed growth review remains a visible required action and freezes the clock",()=>{show(finishRound(act(tick(combinedCompany(),5),{type:"start_growth_wave"})));fireEvent.click(within(screen.getByRole("dialog",{name:"Growth outcome"})).getByRole("button",{name:"Close"}));expect(screen.getByRole("button",{name:"Review growth outcome"})).toBeTruthy();expect(screen.getByRole("button",{name:"Advance 1 step"}).hasAttribute("disabled")).toBe(true);fireEvent.click(screen.getByRole("button",{name:"Review growth outcome"}));fireEvent.click(screen.getByRole("button",{name:"Continue company"}));expect(useGame.getState().game.campaign!.combinedStage!.completedRounds).toHaveLength(1);});
it("keeps final acknowledgement explicit, preserves won reload, and offers inspectable scorecard",()=>{show(finishedCompany());expect(screen.getByRole("region",{name:"Run scorecard"}).textContent).toContain("Ready to complete campaign");expect(screen.getByRole("region",{name:"Run scorecard"}).textContent).not.toContain("Campaign complete");expect(useGame.getState().game.outcome).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Complete campaign"}));expect(screen.getByRole("dialog",{name:"Campaign complete"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Inspect final company"}));expect(screen.getByRole("navigation",{name:"Campaign progression"}).textContent).toContain("Grow the CompanyCombined campaign Completed");fireEvent.click(screen.getByRole("button",{name:"View run scorecard"}));expect(screen.getByRole("region",{name:"Run scorecard"}).textContent).toContain("50,000");expect(loadGame().status).toBe("ok");expect(loadGame().status==="ok"&&(loadGame() as {game:GameState}).game.outcome).toBe("won");});
it("replay preserves prior evidence and uses a distinct run and seed",()=>{const s=act(finishedCompany(),{type:"complete_campaign"});show(s);saveGame(s);saveMeta({...DEFAULT_META,openingOnboarding:{version:1,step:2,status:"completed"}});useGame.getState().newRun();const n=useGame.getState().game;expect(n.campaign!.runId).not.toBe(s.campaign!.runId);expect(n.seed).not.toBe(s.seed);expect(n.campaign!.combinedStage).toBeNull();expect(useGame.getState().measurement.pending.some(e=>e.name==="replay_started")).toBe(false);expect(localStorage.getItem("nn.campaign.analytics.v1")).toContain("run_scorecard");expect(localStorage.getItem("nn.campaign.analytics.v1")).toContain("replay_started");});
