import type { Branch, GameState, TechDef, TechId, TechStatus } from "./types";

export const BRANCHES: { id: Branch; name: string; blurb: string }[] = [
  { id: "growth", name: "Growth", blurb: "More users" },
  { id: "capacity", name: "Capacity", blurb: "Handle more traffic" },
  { id: "reliability", name: "Reliability", blurb: "Survive failures" },
  { id: "engineering", name: "Engineering", blurb: "See more, ship safely" },
];

/**
 * The technology tree. Rows 0-6 are grouped by branch; `requires` may cross
 * branches (autoscaling, automatic failover and canary rollouts all do).
 * Text is kept to a few words: the numbers carry the meaning.
 */
export const TECH: Record<TechId, TechDef> = {
  promotions: {
    id: "promotions",
    name: "Launch Campaigns",
    branch: "growth",
    col: 0,
    row: 0,
    description: "Run big launch campaigns.",
    effects: ["Unlocks Launch campaign: +26% users, +38% traffic"],
    requires: [],
    cost: 3_000,
    effort: 2,
    upkeep: 0,
  },
  analytics: {
    id: "analytics",
    name: "Customer Analytics",
    branch: "growth",
    col: 1,
    row: 0,
    description: "Learn what customers want.",
    effects: ["+15% revenue per user", "Shows growth and churn rates"],
    requires: ["promotions"],
    cost: 6_000,
    effort: 3,
    upkeep: 300,
  },
  targeted: {
    id: "targeted",
    name: "Targeted Campaigns",
    branch: "growth",
    col: 2,
    row: 0,
    description: "Aim campaigns at the right people.",
    effects: ["Unlocks Targeted campaign: +20% users, only +10% traffic"],
    requires: ["analytics"],
    cost: 9_000,
    effort: 4,
    upkeep: 0,
  },

  larger_servers: {
    id: "larger_servers",
    name: "Larger Servers",
    branch: "capacity",
    col: 0,
    row: 1,
    description: "Bigger machines.",
    effects: ["+60% capacity per server", "+30% cost per server"],
    requires: [],
    cost: 5_000,
    effort: 2,
    upkeep: 0,
    upkeepNote: "+30% per server",
  },
  load_balancing: {
    id: "load_balancing",
    name: "Load Balancing",
    branch: "capacity",
    col: 1,
    row: 1,
    description: "Spread traffic evenly across servers.",
    effects: ["Server limit 3 to 12", "+12% capacity"],
    requires: ["larger_servers"],
    cost: 7_000,
    effort: 3,
    upkeep: 500,
  },
  autoscaling: {
    id: "autoscaling",
    name: "Autoscaling",
    branch: "capacity",
    col: 2,
    row: 1,
    description: "Add servers automatically at peak.",
    effects: ["Adds temporary servers above 80% load", "Pay only when they run"],
    requires: ["load_balancing", "monitoring"],
    cost: 12_000,
    effort: 5,
    upkeep: 300,
  },
  caching: {
    id: "caching",
    name: "Caching Layer",
    branch: "capacity",
    col: 0,
    row: 2,
    description: "Serve repeat requests from memory.",
    effects: ["-36% database load"],
    requires: [],
    cost: 6_000,
    effort: 4,
    upkeep: 400,
  },

  backups: {
    id: "backups",
    name: "Automated Backups",
    branch: "reliability",
    col: 0,
    row: 3,
    description: "Nightly database copies.",
    effects: ["A dead database is rebuilt with no data lost"],
    requires: [],
    cost: 3_000,
    effort: 2,
    upkeep: 200,
  },
  replicas: {
    id: "replicas",
    name: "Database Replica",
    branch: "reliability",
    col: 1,
    row: 3,
    description: "A live copy of the database.",
    effects: ["+35% database capacity", "Can take over if the primary dies"],
    requires: ["backups"],
    cost: 9_000,
    effort: 4,
    upkeep: 0,
    upkeepNote: "half the database cost",
  },
  auto_failover: {
    id: "auto_failover",
    name: "Automatic Failover",
    branch: "reliability",
    col: 2,
    row: 3,
    description: "Spares take over by themselves.",
    effects: ["Dead machines are replaced in seconds", "No incident, nobody paged"],
    requires: ["replicas", "health_checks"],
    cost: 10_000,
    effort: 5,
    upkeep: 300,
  },
  standby: {
    id: "standby",
    name: "Standby Server",
    branch: "reliability",
    col: 0,
    row: 4,
    description: "A spare server kept warm.",
    effects: ["Can take over a dead server", "Extra capacity in an overload"],
    requires: [],
    cost: 4_000,
    effort: 2,
    upkeep: 0,
    upkeepNote: "one server's cost",
  },
  health_checks: {
    id: "health_checks",
    name: "Health Checks",
    branch: "reliability",
    col: 1,
    row: 4,
    description: "Spot sick machines fast.",
    effects: ["With a load balancer, dead servers are replaced automatically", "Names the failing machine"],
    requires: ["monitoring"],
    cost: 3_000,
    effort: 2,
    upkeep: 0,
  },

  monitoring: {
    id: "monitoring",
    name: "Monitoring",
    branch: "engineering",
    col: 0,
    row: 5,
    description: "See what your system is doing.",
    effects: ["Exact load numbers and a forecast", "Investigate incidents 3x faster"],
    requires: [],
    cost: 4_000,
    effort: 3,
    upkeep: 300,
  },
  tracing: {
    id: "tracing",
    name: "Request Tracing",
    branch: "engineering",
    col: 1,
    row: 5,
    description: "Follow requests end to end.",
    effects: ["Flags the faulty equipment in incidents", "Near-instant investigation"],
    requires: ["monitoring"],
    cost: 7_000,
    effort: 4,
    upkeep: 300,
  },
  code_health: {
    id: "code_health",
    name: "Code Health",
    branch: "engineering",
    col: 0,
    row: 6,
    description: "Code review and tidy-up habits.",
    effects: ["Tech debt grows half as fast", "Debt paydown removes 20, not 14"],
    requires: [],
    cost: 2_000,
    effort: 3,
    upkeep: 0,
  },
  deploy_testing: {
    id: "deploy_testing",
    name: "Automated Testing",
    branch: "engineering",
    col: 1,
    row: 6,
    description: "Tests run on every change.",
    effects: ["Deploy risk nearly halved", "Testing takes half the time"],
    requires: ["code_health"],
    cost: 5_000,
    effort: 4,
    upkeep: 200,
  },
  safer_rollouts: {
    id: "safer_rollouts",
    name: "Canary Rollouts",
    branch: "engineering",
    col: 2,
    row: 6,
    description: "Try each release on a few users first.",
    effects: ["Bad releases roll back automatically", "No more regression incidents"],
    requires: ["deploy_testing", "standby"],
    cost: 9_000,
    effort: 5,
    upkeep: 200,
  },
};

export const TECH_ORDER: TechId[] = Object.keys(TECH) as TechId[];

export function has(state: Pick<GameState, "techDone">, tech: TechId): boolean {
  return state.techDone.includes(tech);
}

export function techStatus(state: GameState, id: TechId): TechStatus {
  if (has(state, id)) return "done";
  if (state.releases.some((r) => r.techId === id)) return "ready";
  if (state.tasks.some((t) => t.kind === "tech" && t.techId === id)) return "in_progress";
  const def = TECH[id];
  return def.requires.every((r) => has(state, r)) ? "available" : "locked";
}

export function missingPrerequisites(state: GameState, id: TechId): TechId[] {
  return TECH[id].requires.filter((r) => !has(state, r));
}
