import {it,expect} from "vitest";
import {applyAction,newGame,type GameState} from "../index";
import {pendingCombined} from "../combinedCampaign";
import {act,tick,finishRound,sequence,completedReliability,strategyPredecessor} from "./combinedFixture";
import {validateEnvelope,makeEnvelope} from "@/game/saveMigrations";
function strategyEvidence(s:GameState){let cash=2000000,minCash=cash;const acquisitions=[];for(const e of s.campaign!.trace){if(e.type==="action-requested"){cash-=Number(e.data.costCents);if(Number(e.data.costCents)>0)acquisitions.push({step:e.step,type:e.data.type,costCents:e.data.costCents,activationStep:e.data.activationStep});}if(e.type==="settlement")cash+=Number(e.data.netCents);minCash=Math.min(minCash,cash);}expect(cash).toBe(s.campaign!.cashCents);return {minCash,acquisitions};}
function campaign(s:GameState){for(let i=0;i<3;i++){s=tick(s,5);s=act(s,{type:"start_growth_wave"});s=finishRound(s);s=act(s,{type:"acknowledge_growth"});}s=tick(s,5);expect(pendingCombined(s.campaign)).toBe(true);return act(s,{type:"complete_campaign"});}
it("balance: vertical without cache and base-app/cache strategies both finish solvent through public purchases",()=>{const a=campaign(act(strategyPredecessor(false),{type:"enter_combined",sequence}));let b=act(strategyPredecessor(true),{type:"enter_combined",sequence});b=tick(act(b,{type:"add_server"}),2);b=tick(act(b,{type:"set_routing",mode:"balanced",targets:b.campaign!.apps.map(a=>a.id)}),1);b=tick(act(b,{type:"start_db_upgrade"}),4);b=campaign(b);expect(a.outcome).toBe("won");expect(b.outcome).toBe("won");expect(a.campaign!.cashCents).toBeGreaterThan(0);expect(b.campaign!.cashCents).toBeGreaterThan(0);expect(a.campaign!.readCache).toBeNull();expect(b.campaign!.readCache!.tuned).toBe(true);expect(a.campaign!.apps.map(a=>a.capacity)).not.toEqual(b.campaign!.apps.map(a=>a.capacity));console.log("Phase 7 strategies",[a,b].map(s=>({...strategyEvidence(s),runId:s.campaign!.runId,seed:s.seed,cash:s.campaign!.cashCents,failed:s.campaign!.cumulative.failed,rejected:s.campaign!.cumulative.rejected,setup:s.campaign!.investedCents,architecture:s.campaign!.apps.map(a=>a.capacity),cache:s.campaign!.readCache,step:s.campaign!.step,coverage:s.campaign!.scorecard!.measurement.scope})));},15000);
it("balance: the stranded Scaling company can accept risk, earn actual settlement revenue and fund headroom",()=>{let s=tick(newGame(9999),6);s=act(s,{type:"start_db_upgrade"});while(s.phase!=="review")s=tick(s);s=act(s,{type:"acknowledge_review"});s=act(s,{type:"acknowledge_milestone"});s=tick(act(s,{type:"set_traffic_limit",enabled:true}),1);s=tick(s,300-s.campaign!.step);s=tick(act(s,{type:"add_server"}),2);s=tick(act(s,{type:"scale_up",appId:"app-1"}),3);expect(s.campaign!.cashCents).toBe(159334);expect(s.campaign!.step).toBe(305);const old=structuredClone(s);expect(applyAction(s,{type:"start_db_upgrade"}).ok).toBe(false);s=act(s,{type:"accept_scaling_risk"});expect(s.campaign!.cashCents).toBe(old.campaign!.cashCents);expect(s.campaign!.step).toBe(old.campaign!.step);s=tick(s,4);expect(s.campaign!.scaling!.consumed).toBe(true);s=tick(act(s,{type:"set_traffic_limit",enabled:false}),1);for(let i=0;i<180&&s.campaign!.cashCents<=300000;i++){if(s.phase==="review")s=act(s,{type:"acknowledge_review"});s=tick(s);expect(s.phase).not.toBe("ended");}expect(s.campaign!.cashCents).toBeGreaterThan(300000);expect(applyAction(s,{type:"start_db_upgrade"}).ok).toBe(true);expect(s.campaign!.settlements.length).toBeGreaterThan(old.campaign!.settlements.length);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
it.each([0,1,2])("balance: each bounded template can lead the same company, permutation %i",shift=>{const config=[...sequence.slice(shift),...sequence.slice(0,shift)];const s=act(completedReliability(),{type:"enter_combined",sequence:config});expect(campaign(s).outcome).toBe("won");},15000);

const orders=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];
it.each(orders)("balance: all peak/duration bounds for pool order %j",(...order)=>{const predecessor=completedReliability();for(const read of [3800,4000])for(const failure of [3400,3600])for(let mask=0;mask<8;mask++){const pool=[{template:"read-growth-pulse" as const,peak:read,duration:(mask&1?16:12) as 12|16},{template:"write-pressure" as const,peak:3000,duration:(mask&2?16:12) as 12|16},{template:"failure-under-load" as const,peak:failure,duration:(mask&4?16:12) as 12|16}];const s=act(predecessor,{type:"enter_combined",sequence:order.map(i=>pool[i])});expect(campaign(s).outcome).toBe("won");}},120000);
