import {describe,it,expect} from "vitest";
import {applyAction,newGame} from "../index";
import {step,advanceSteps} from "../step";
import {canRetire} from "../autoscaling";
import {canEnterCombined,combinedInput,canStartGrowth,pendingCombined} from "../combinedCampaign";
import {baselineDemand,growthUsers,sequenceValid} from "../scenarios/combinedCampaign";
import {captureScorecard,emptyServiceMeasurement,observeService} from "../campaignScorecard";
import {makeEnvelope,validateEnvelope} from "@/game/saveMigrations";
import {act,tick,completedReliability,combinedCompany,finishRound,finishedCompany,sequence} from "./combinedFixture";
describe("Combined campaign",()=>{
 it("enters explicitly with the same company, resources, ownership and history",()=>{const p=completedReliability(),before=structuredClone(p);const s=act(p,{type:"enter_combined"});expect(p).toEqual(before);expect(canEnterCombined(p)).toBe(true);expect(s.campaign!.runId).toBe(p.campaign!.runId);expect(s.campaign!.cashCents).toBe(p.campaign!.cashCents);expect(s.campaign!.apps).toEqual(p.campaign!.apps);expect(s.campaign!.reliabilityStage).toEqual(p.campaign!.reliabilityStage);expect(s.campaign!.combinedStage!.users).toBe(2000);expect(sequenceValid(s.campaign!.combinedStage!.sequence)).toBe(true);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
 it("rejects premature entry without changing the company",()=>{const s=newGame(1);expect(applyAction(s,{type:"enter_combined"}).ok).toBe(false);expect(s.campaign!.combinedStage).toBeNull();});
 it("uses the approved registration and baseline progression",()=>{expect([0,1,2].map(i=>growthUsers(50000,i))).toEqual([20000,35000,50000]);expect([2000,20000,35000,50000].map(u=>baselineDemand(u,50000))).toEqual([2400,2625,2812,3000]);});
 it("requires five new full-demand readiness steps before a player starts pressure",()=>{let s=combinedCompany();expect(canStartGrowth(s)).toBe(false);s=tick(s,4);expect(applyAction(s,{type:"start_growth_wave"}).ok).toBe(false);s=tick(s);expect(canStartGrowth(s)).toBe(true);const n=s.campaign!.step;s=act(s,{type:"start_growth_wave"});expect(s.campaign!.step).toBe(n);expect(s.campaign!.combinedStage!.currentRound!.startStep).toBe(n+8);s=tick(s,7);expect(s.campaign!.incomingRate).toBe(2400);s=tick(s);expect(s.users).toBe(20000);expect(s.campaign!.incomingRate).toBe(4000);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
 it("collects observed outcomes, pauses for acknowledgement and never completes automatically",()=>{let s=tick(combinedCompany(),5);s=finishRound(act(s,{type:"start_growth_wave"}));expect(pendingCombined(s.campaign)).toBe(true);expect(advanceSteps(s,10).stepsConsumed).toBe(0);expect(step(s).state).toBe(s);expect(s.phase).not.toBe("ended");expect(applyAction(s,{type:"run_promotion"}).ok).toBe(false);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");s=act(s,{type:"acknowledge_growth"});expect(s.campaign!.combinedStage!.completedRounds).toHaveLength(1);expect(s.campaign!.combinedStage!.readinessSteps).toBe(0);});
 it("requires all three reviews, five final steps and final explicit acknowledgement",()=>{let s=finishedCompany();expect(s.campaign!.combinedStage!.finalReview).not.toBeNull();expect(s.phase).toBe("management");expect(s.users).toBe(50000);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");s=act(s,{type:"complete_campaign"});expect(s.phase).toBe("ended");expect(s.outcome).toBe("won");expect(s.campaign!.scorecard).toEqual(captureScorecard(s,"won"));expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");expect(applyAction(s,{type:"complete_campaign"}).ok).toBe(false);expect(step(s).state).toBe(s);});
 it("promotion has one paid request, delayed activation, bounded duration and cooldown",()=>{let s=combinedCompany();const n=s.campaign!.step,cash=s.campaign!.cashCents;s=act(s,{type:"run_promotion"});expect(s.campaign!.cashCents).toBe(cash-50000);expect(s.users).toBe(2000);expect(s.campaign!.incomingRate).toBe(2400);s=tick(s);expect(s.campaign!.incomingRate).toBe(2800);expect(s.campaign!.promotion!.activatedStep).toBe(n+1);expect(applyAction(s,{type:"start_growth_wave"}).ok).toBe(false);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");s=tick(s,12);expect(s.campaign!.incomingRate).toBe(2400);expect(combinedInput(s.campaign!)).toBe(2400);expect(applyAction(s,{type:"run_promotion"}).ok).toBe(false);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
 it("reproduces the exact combined sequence and final scorecard from the same seed and decisions",()=>{expect(finishedCompany()).toEqual(finishedCompany());});
});

it("limiting remains a business trade-off and cannot qualify readiness or final success",()=>{let s=combinedCompany();s=tick(act(s,{type:"set_traffic_limit",enabled:true}),8);expect(s.campaign!.combinedStage!.readinessSteps).toBe(0);expect(applyAction(s,{type:"start_growth_wave"}).ok).toBe(false);expect(s.campaign!.cumulative.rejected).toBeGreaterThan(0);});
it("promotion cannot overlap an announced wave and registration alone never finishes the campaign",()=>{let s=tick(combinedCompany(),5);s=act(s,{type:"start_growth_wave"});expect(applyAction(s,{type:"run_promotion"}).ok).toBe(false);s=tick(s,8);expect(applyAction(s,{type:"complete_campaign"}).ok).toBe(false);});
it("failure-under-load preserves the teaching test and restores only the current target",()=>{const p=completedReliability();let s=act(p,{type:"enter_combined",sequence:[sequence[2],sequence[0],sequence[1]]});s=act(tick(s,5),{type:"start_growth_wave"});const old=structuredClone(s.campaign!.reliabilityStage!.fault);s=tick(s,8);const f=s.campaign!.combinedStage!.currentRound!.fault!;expect(s.campaign!.apps.find(a=>a.id===f.targetId)!.health).toBe("failed");expect(s.campaign!.reliabilityStage!.fault).toEqual(old);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");s=act(s,{type:"restore_app",appId:f.targetId});s=tick(s,3);expect(s.campaign!.combinedStage!.currentRound!.fault!.restoreSource).toBe("manual");expect(s.campaign!.reliabilityStage!.fault).toEqual(old);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
it("counts only fresh eligible observations and reports incomplete historical coverage honestly",()=>{const s=tick(newGame(3),3),m=emptyServiceMeasurement(3,"since-upgrade");observeService(m,s.campaign!.snapshot);observeService(m,s.campaign!.snapshot);expect(m.eligibleSteps).toBe(1);s.campaign!.serviceMeasurement=m;const card=captureScorecard(s,"bankrupt");expect(card.wholeRunUptime).toBeNull();expect(card.wholeRunLargestOutage).toBeNull();expect(card.measurement.healthySteps).toBe(1);});
it("captures exact settled finances separately from pending revenue and promotions",()=>{let s=combinedCompany();s=tick(act(s,{type:"run_promotion"}),13);const card=captureScorecard(s,"bankrupt"),c=s.campaign!;expect(card.promotionCents).toBe(50000);expect(card.infrastructureSetupCents).toBe(c.investedCents-50000);expect(card.revenueCents).toBe(c.revenueCents);expect(card.pendingRevenueCents).toBe(c.ledger.successes*20);expect(card.salaryCents+card.infrastructureOperatingCents).toBe(c.costsCents);});

it("keeps authoritative full-run service history beyond the 600-snapshot display window",()=>{const s=tick(combinedCompany(),700),c=s.campaign!,card=captureScorecard(s,"bankrupt");expect(c.recent).toHaveLength(600);expect(card.measurement.eligibleSteps).toBe(c.step);expect(card.wholeRunUptime).not.toBeNull();expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");},60000);
it("runs the existing delayed controller on actual combined demand and healthy routed capacity",()=>{let s=act(combinedCompany(),{type:"unlock_autoscaling"});s=tick(act(s,{type:"deploy_autoscaler"}),2);s=tick(s,5);s=act(s,{type:"start_growth_wave"});const r=s.campaign!.combinedStage!.currentRound!;s=tick(s,r.startStep+2-s.campaign!.step);const request=s.campaign!.pending.find(a=>a.type==="add-app"&&a.source==="autoscaler")!;expect(request).toBeTruthy();expect(request.activationStep).toBe(request.requestedStep+3);s=tick(s,3);expect(s.campaign!.apps.find(a=>a.id===request.targetId)!.routed).toBe(false);expect(s.campaign!.pending.find(a=>a.type==="routing")!.activationStep).toBe(request.requestedStep+4);s=tick(s);expect(s.campaign!.apps.find(a=>a.id===request.targetId)!.routed).toBe(true);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
it("continues controller observations during combined failure instead of suspending for the completed teaching test",()=>{let s=act(completedReliability(),{type:"enter_combined",sequence:[sequence[2],sequence[0],sequence[1]]});s=act(s,{type:"unlock_autoscaling"});s=tick(act(s,{type:"deploy_autoscaler"}),2);s=act(tick(s,5),{type:"start_growth_wave"});s=tick(s,10);expect(s.campaign!.snapshot.spikes!.routedBusyBasisPoints).toBe(7500);expect(s.campaign!.snapshot.instances!.filter(a=>a.health==="healthy").reduce((n,a)=>n+a.capacity,0)).toBe(3200);expect(s.campaign!.spikeStage!.controller!.highSteps).toBe(0);expect(s.campaign!.spikeStage!.controller!.blockedReason).not.toBe("Reliability test in progress");expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
it("pins a real autoscaled future fault target against retirement without inventing another app",()=>{let s=act(combinedCompany(),{type:"unlock_autoscaling"});s=tick(act(s,{type:"deploy_autoscaler"}),2);s=act(tick(s,5),{type:"start_growth_wave"});s=tick(s,16);s=act(s,{type:"set_autoscaling",enabled:false});s=finishRound(s);s=act(s,{type:"acknowledge_growth"});s=act(tick(s,5),{type:"start_growth_wave"});s=finishRound(s);s=act(s,{type:"acknowledge_growth"});s=act(tick(s,5),{type:"start_growth_wave"});const target=s.campaign!.combinedStage!.currentRound!.fault!.targetId;expect(s.campaign!.spikeStage!.controller!.managedAppIds).toContain(target);expect(canRetire(s.campaign!,target)).toBe(false);expect(validateEnvelope(makeEnvelope(s)).status).toBe("ok");});
