import { test, expect, savedGame, seedSave } from "./fixtures";
import { applyAction, newGame } from "../src/sim";
import { advanceSteps } from "../src/sim/step";

test("keyboard introduction stays paused, contains focus and remembers completion", async ({ page }) => {
  await page.goto("/");
  expect(await page.evaluate(() => localStorage.getItem("nn.campaign.save.v1"))).toBeNull();
  const preview = page.getByRole("img", { name: /furnished office/ });
  await expect(preview).toBeVisible();
  await expect.poll(() => preview.evaluate(el => (el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({ path: "test-results/phase2-title.png" });
  await page.getByRole("button", { name: "Try Prototype" }).press("Enter");
  const intro = page.getByRole("dialog", { name: "Company introduction" });
  await expect(intro).toContainText("Prompt 1 of 3");
  await page.keyboard.press("p");
  expect((await savedGame(page)).campaign!.step).toBe(0);
  await intro.getByRole("button", { name: "Next", exact: true }).focus();
  await page.keyboard.press("Tab");
  await expect(intro.getByRole("button", { name: "Close" })).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(intro.getByRole("button", { name: "Next", exact: true })).toBeFocused();
  await page.keyboard.press("Enter");
  await intro.getByRole("button", { name: "Back", exact: true }).press("Enter");
  await expect(intro).toContainText("Prompt 1 of 3");
  await intro.getByRole("button", { name: "Next", exact: true }).press("Enter");
  await intro.getByRole("button", { name: "Next", exact: true }).press("Enter");
  await intro.getByRole("button", { name: "Finish introduction" }).press("Enter");
  await expect(intro).toBeHidden();
  await expect(page.getByRole("button", { name: "Run", exact: true })).toBeVisible();
  expect((await savedGame(page)).campaign!.step).toBe(0);
  await page.screenshot({ path: "test-results/phase2-healthy.png" });
  await page.getByRole("button", { name: "Menu", exact: true }).click();
  await page.screenshot({ path: "test-results/phase2-menu.png" });
  await page.reload(); await page.getByRole("button", { name: "Continue company" }).click();
  await expect(intro).toBeHidden();
});

test("pending milestone reload keeps the company paused and awards it only once", async ({ page }) => {
  const incident = advanceSteps(newGame(1, "pending-milestone"), 6).state;
  const response = applyAction(incident, { type: "start_db_upgrade" });
  if (!response.ok) throw Error(response.message);
  const review = advanceSteps(response.state, 30).state;
  await seedSave(page, review); await page.goto("/");
  await page.getByRole("button", { name: "Continue company" }).click();
  const report = page.getByRole("dialog", { name: "Incident postmortem" });
  await page.screenshot({ path: "test-results/phase2-report.png" });
  await report.getByRole("button", { name: "Continue company" }).click();
  const before = await savedGame(page);
  await page.reload(); await page.getByRole("button", { name: "Continue company" }).click();
  await expect(page.getByRole("dialog", { name: "First growth challenge handled" })).toBeVisible();
  expect(await savedGame(page)).toEqual(before);
  await page.getByRole("button", { name: "Continue operating" }).click();
  const after = await savedGame(page);
  expect(after.campaign!.runId).toBe(before.campaign!.runId);
  expect(after.campaign!.step).toBe(before.campaign!.step);
  expect(after.campaign!.cashCents).toBe(before.campaign!.cashCents);
  expect(after.campaign!.trace.filter(e => e.type === "milestone-awarded")).toHaveLength(1);
  await page.getByRole("button", { name: "History", exact: true }).click();
  await page.screenshot({ path: "test-results/phase2-history.png" });
});
